apiVersion: v1
kind: ConfigMap
metadata:
  name: opa
  namespace: opa
  labels:
    name: opa
data:
  config.yaml: |
    services:
      - name: opa
        url: https://gitlab.com/ecimino/opa-football-rego/-/archive/main/
    bundles:
      football:
        service: opa
        resource: opa-football-rego-main.tar.gz
        persist: true
        polling:
          min_delay_seconds: 15
          max_delay_seconds: 30
    decision_logs:
      console: false